In [1]:
import pandas as pd
import numpy as np
import yaml
from datetime import datetime, timedelta

In [2]:
data_swissre = pd.read_csv('final_data.csv', parse_dates=['date'])
data_swissre

/Users/francescoposa/opt/anaconda3/envs/personal/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (70,71,72,73,74,75,76,77,78) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,EpiVacCorona,Pfizer/BioNTech,CanSino,Soberana02,QazVac,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations,vaccines_available
0,2020-03-12,Aruba,AW,2,0.0,2.0,NaN,0.0,104341.0,987.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0
1,2020-03-13,Aruba,AW,2,0.0,2.0,0.0,0.0,104341.0,987.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0
2,2020-03-14,Aruba,AW,2,0.0,2.0,0.0,0.0,104341.0,987.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0
3,2020-03-15,Aruba,AW,2,0.0,2.0,0.0,0.0,104341.0,987.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0
4,2020-03-16,Aruba,AW,2,0.0,2.0,0.0,0.0,104341.0,987.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80433,2021-05-27,Zimbabwe,ZW,38854,1592.0,36541.0,35.0,3.0,14645473.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.065098,0.044254,0.020844,0.000839,1
80434,2021-05-28,Zimbabwe,ZW,38918,1592.0,36563.0,64.0,0.0,14645473.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.066696,0.044835,0.021861,0.000867,1
80435,2021-05-29,Zimbabwe,ZW,38933,1594.0,36576.0,15.0,2.0,14645473.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.068449,0.045528,0.022920,0.000960,1
80436,2021-05-30,Zimbabwe,ZW,38944,1594.0,36589.0,11.0,0.0,14645473.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.069098,0.045799,0.023299,0.000985,1
80437,2021-05-31,Zimbabwe,ZW,38961,1594.0,36594.0,17.0,0.0,14645473.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.069651,0.046136,0.023516,0.001026,1

In [3]:
data_swissre[(data_swissre['iso_code'] == 'CHE')]

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,EpiVacCorona,Pfizer/BioNTech,CanSino,Soberana02,QazVac,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations,vaccines_available
13628,2020-02-25,Switzerland,CH,1,0.0,1.0,1.0,0.0,8319769.0,86914.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0
13629,2020-02-26,Switzerland,CH,1,0.0,1.0,0.0,0.0,8319769.0,86914.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0
13630,2020-02-27,Switzerland,CH,8,0.0,8.0,7.0,0.0,8319769.0,86914.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0
13631,2020-02-28,Switzerland,CH,12,0.0,12.0,4.0,0.0,8319769.0,86914.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0
13632,2020-02-29,Switzerland,CH,18,0.0,18.0,6.0,0.0,8319769.0,86914.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14085,2021-05-27,Switzerland,CH,692111,10798.0,641069.0,992.0,9.0,8319769.0,86914.0,...,0.0,1.0,0.0,0.0,0.0,0.566217,0.353419,0.212798,0.009210,1
14086,2021-05-28,Switzerland,CH,693023,10801.0,644115.0,912.0,3.0,8319769.0,86914.0,...,0.0,1.0,0.0,0.0,0.0,0.578864,0.359751,0.219113,0.009266,1
14087,2021-05-29,Switzerland,CH,693023,10805.0,645318.0,0.0,4.0,8319769.0,86914.0,...,0.0,1.0,0.0,0.0,0.0,0.585422,0.363212,0.222210,0.009384,1
14088,2021-05-30,Switzerland,CH,693023,10806.0,645321.0,0.0,1.0,8319769.0,86914.0,...,0.0,1.0,0.0,0.0,0.0,0.588386,0.364905,0.223481,0.009486,1
14089,2021-05-31,Switzerland,CH,694740,10810.0,647035.0,1717.0,4.0,8319769.0,86914.0,...,0.0,1.0,0.0,0.0,0.0,0.599596,0.370306,0.229290,0.010219,1

In [4]:
with open('../config/r_estim_features.yaml', 'r', encoding='utf-8') as file:
    swissre_features = yaml.load(file, Loader=yaml.FullLoader)

In [5]:
# Using as economic indicator unemployment rate. Interpolating the quarterly data.
unemp = data_swissre[['date', 'iso_code', 'unemployment_rate_2019_12_31', 'unemployment_rate_2020_03_31', 'unemployment_rate_2020_06_30', 'unemployment_rate_2020_09_30', 'unemployment_rate_2020_12_31', 'unemployment_rate_2021_03_31', 'unemployment_rate_2021_06_30']]

In [6]:
unemp = unemp[~unemp.unemployment_rate_2020_03_31.isna()]
unemp

,date,iso_code,unemployment_rate_2019_12_31,unemployment_rate_2020_03_31,unemployment_rate_2020_06_30,unemployment_rate_2020_09_30,unemployment_rate_2020_12_31,unemployment_rate_2021_03_31,unemployment_rate_2021_06_30
2248,2020-01-26,ARE,2.68,2.61,2.87,2.8,2.70,2.70,2.69
2249,2020-01-27,ARE,2.68,2.61,2.87,2.8,2.70,2.70,2.69
2250,2020-01-28,ARE,2.68,2.61,2.87,2.8,2.70,2.70,2.69
2251,2020-01-29,ARE,2.68,2.61,2.87,2.8,2.70,2.70,2.69
2252,2020-01-30,ARE,2.68,2.61,2.87,2.8,2.70,2.70,2.69
...,...,...,...,...,...,...,...,...,...
79996,2021-05-27,ZMB,11.49,11.16,10.82,10.5,10.56,11.09,11.68
79997,2021-05-28,ZMB,11.49,11.16,10.82,10.5,10.56,11.09,11.68
79998,2021-05-29,ZMB,11.49,11.16,10.82,10.5,10.56,11.09,11.68
79999,2021-05-30,ZMB,11.49,11.16,10.82,10.5,10.56,11.09,11.68
80000,2021-05-31,ZMB,11.49,11.16,10.82,10.5,10.56,11.09,11.68

In [7]:
eco = ['unemployment_rate_2020_03_31', 'unemployment_rate_2020_06_30', 'unemployment_rate_2020_09_30', 'unemployment_rate_2020_12_31', 'unemployment_rate_2021_03_31', 'unemployment_rate_2021_06_30']
#for i, indicator in enumerate(reversed(eco[1:])):
    #unemp[indicator] = unemp[indicator] - unemp[eco[-(i+2)]]
    
for indicator in eco:
    unemp[indicator] = unemp[indicator] - unemp['unemployment_rate_2019_12_31']

In [8]:
unemp['unemployment_rate_2019_12_31'] = 0
unemp

,date,iso_code,unemployment_rate_2019_12_31,unemployment_rate_2020_03_31,unemployment_rate_2020_06_30,unemployment_rate_2020_09_30,unemployment_rate_2020_12_31,unemployment_rate_2021_03_31,unemployment_rate_2021_06_30
2248,2020-01-26,ARE,0,-0.07,0.19,0.12,0.02,0.02,0.01
2249,2020-01-27,ARE,0,-0.07,0.19,0.12,0.02,0.02,0.01
2250,2020-01-28,ARE,0,-0.07,0.19,0.12,0.02,0.02,0.01
2251,2020-01-29,ARE,0,-0.07,0.19,0.12,0.02,0.02,0.01
2252,2020-01-30,ARE,0,-0.07,0.19,0.12,0.02,0.02,0.01
...,...,...,...,...,...,...,...,...,...
79996,2021-05-27,ZMB,0,-0.33,-0.67,-0.99,-0.93,-0.40,0.19
79997,2021-05-28,ZMB,0,-0.33,-0.67,-0.99,-0.93,-0.40,0.19
79998,2021-05-29,ZMB,0,-0.33,-0.67,-0.99,-0.93,-0.40,0.19
79999,2021-05-30,ZMB,0,-0.33,-0.67,-0.99,-0.93,-0.40,0.19
80000,2021-05-31,ZMB,0,-0.33,-0.67,-0.99,-0.93,-0.40,0.19

In [9]:
unemp[unemp['iso_code'] == 'ESP']

,date,iso_code,unemployment_rate_2019_12_31,unemployment_rate_2020_03_31,unemployment_rate_2020_06_30,unemployment_rate_2020_09_30,unemployment_rate_2020_12_31,unemployment_rate_2021_03_31,unemployment_rate_2021_06_30
24077,2020-01-31,ESP,0,3.12,11.37,7.53,3.7,3.31,2.46
24078,2020-02-01,ESP,0,3.12,11.37,7.53,3.7,3.31,2.46
24079,2020-02-02,ESP,0,3.12,11.37,7.53,3.7,3.31,2.46
24080,2020-02-03,ESP,0,3.12,11.37,7.53,3.7,3.31,2.46
24081,2020-02-04,ESP,0,3.12,11.37,7.53,3.7,3.31,2.46
...,...,...,...,...,...,...,...,...,...
24559,2021-05-27,ESP,0,3.12,11.37,7.53,3.7,3.31,2.46
24560,2021-05-28,ESP,0,3.12,11.37,7.53,3.7,3.31,2.46
24561,2021-05-29,ESP,0,3.12,11.37,7.53,3.7,3.31,2.46
24562,2021-05-30,ESP,0,3.12,11.37,7.53,3.7,3.31,2.46
24563,2021-05-31,ESP,0,3.12,11.37,7.53,3.7,3.31,2.46

In [10]:
iso_list = unemp.iso_code.unique()
dates = list(pd.date_range('2020-03-31', '2021-06-30').strftime('%Y-%m-%d'))
dates_total = dates*len(iso_list)
iso_list_total = list(np.array([[iso_code]*len(dates) for iso_code in iso_list]).flatten())
unemployment_rate_idx= [np.nan for i in iso_list_total]

In [11]:
df = pd.DataFrame({'iso_code': iso_list_total, 'date':dates_total, 'unemployment_rate_idx':unemployment_rate_idx})

In [12]:
for iso_code in iso_list:
    #df['unemployment_rate_idx'] = np.where((df['iso_code']== iso_code)&(df['date'] == '2019-12-31'), unemp[unemp['iso_code'] == iso_code]['unemployment_rate_2019_12_31'].values[0], df['unemployment_rate_idx'])
    df['unemployment_rate_idx'] = np.where((df['iso_code']== iso_code)&(df['date'] == '2020-03-31'), unemp[unemp['iso_code'] == iso_code]['unemployment_rate_2020_03_31'].values[0], df['unemployment_rate_idx'])
    df['unemployment_rate_idx'] = np.where((df['iso_code']== iso_code)&(df['date'] == '2020-06-30'), unemp[unemp['iso_code'] == iso_code]['unemployment_rate_2020_06_30'].values[0], df['unemployment_rate_idx'])
    df['unemployment_rate_idx'] = np.where((df['iso_code']== iso_code)&(df['date'] == '2020-09-30'), unemp[unemp['iso_code'] == iso_code]['unemployment_rate_2020_09_30'].values[0], df['unemployment_rate_idx'])
    df['unemployment_rate_idx'] = np.where((df['iso_code']== iso_code)&(df['date'] == '2020-12-31'), unemp[unemp['iso_code'] == iso_code]['unemployment_rate_2020_12_31'].values[0], df['unemployment_rate_idx'])
    df['unemployment_rate_idx'] = np.where((df['iso_code']== iso_code)&(df['date'] == '2021-03-31'), unemp[unemp['iso_code'] == iso_code]['unemployment_rate_2021_03_31'].values[0], df['unemployment_rate_idx'])
    df['unemployment_rate_idx'] = np.where((df['iso_code']== iso_code)&(df['date'] == '2021-06-30'), unemp[unemp['iso_code'] == iso_code]['unemployment_rate_2021_06_30'].values[0], df['unemployment_rate_idx'])

In [13]:
df['unemployment_rate_idx'] = df['unemployment_rate_idx'].interpolate(method='linear')
df['date'] =pd.to_datetime(df['date'])

In [14]:
df.to_csv('unemp_daily_with_forecast.csv', index=False)

In [15]:
final = data_swissre.merge(df, on=['iso_code', 'date'])
final[final['iso_code'] == 'ITA']

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,Pfizer/BioNTech,CanSino,Soberana02,QazVac,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations,vaccines_available,unemployment_rate_idx
17931,2020-03-31,Italy,IT,105792,12428.0,15729.0,4053.0,837.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.470000
17932,2020-04-01,Italy,IT,110574,13155.0,16847.0,4782.0,727.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.484066
17933,2020-04-02,Italy,IT,115242,13915.0,18278.0,4668.0,760.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.498132
17934,2020-04-03,Italy,IT,119827,14681.0,19758.0,4585.0,766.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.512198
17935,2020-04-04,Italy,IT,124632,15362.0,20996.0,4805.0,681.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.526264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18353,2021-05-27,Italy,IT,4205970,125793.0,3826984.0,4143.0,171.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.547490,0.370232,0.177257,0.008359,1,3.494725
18354,2021-05-28,Italy,IT,4209707,125919.0,3837518.0,3737.0,126.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.557260,0.375563,0.181697,0.008414,1,3.492527
18355,2021-05-29,Italy,IT,4213055,126002.0,3845087.0,3348.0,83.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.565890,0.380836,0.185054,0.008426,1,3.490330
18356,2021-05-30,Italy,IT,4216003,126046.0,3851661.0,2948.0,44.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.572509,0.385052,0.187458,0.008414,1,3.488132
18357,2021-05-31,Italy,IT,4217821,126128.0,3858019.0,1818.0,82.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.580401,0.390439,0.189962,0.008449,1,3.485934

In [16]:
quarters = [('2020-03-31', '2020-06-30'), ('2020-06-30', '2020-09-30'), 
            ('2020-09-30', '2020-12-31'), ('2020-12-31', '2021-03-31'), 
            ('2021-03-31', '2021-06-30')]

In [17]:
weights_df = pd.DataFrame({'date':dates, 'weight':[1 for i in range(len(dates))]})
weights_df['date'] = pd.to_datetime(weights_df['date']).dt.date
epsilon = 1e-4
for quarter in quarters:
    start = datetime.strptime(quarter[0], '%Y-%m-%d').date()
    end = datetime.strptime(quarter[1], '%Y-%m-%d').date()
    interval_size = (end-start).days
    denominator = interval_size/2
    for i in range(interval_size):
        w = (np.abs(denominator-i) / denominator) + epsilon
        weights_df['weight'] = np.where(weights_df['date'] == start + timedelta(days=i), w, weights_df['weight'])

In [18]:
final['date'] = pd.to_datetime(final['date']).dt.date
final[final['iso_code'] == 'ITA']

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,Pfizer/BioNTech,CanSino,Soberana02,QazVac,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations,vaccines_available,unemployment_rate_idx
17931,2020-03-31,Italy,IT,105792,12428.0,15729.0,4053.0,837.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.470000
17932,2020-04-01,Italy,IT,110574,13155.0,16847.0,4782.0,727.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.484066
17933,2020-04-02,Italy,IT,115242,13915.0,18278.0,4668.0,760.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.498132
17934,2020-04-03,Italy,IT,119827,14681.0,19758.0,4585.0,766.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.512198
17935,2020-04-04,Italy,IT,124632,15362.0,20996.0,4805.0,681.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.526264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18353,2021-05-27,Italy,IT,4205970,125793.0,3826984.0,4143.0,171.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.547490,0.370232,0.177257,0.008359,1,3.494725
18354,2021-05-28,Italy,IT,4209707,125919.0,3837518.0,3737.0,126.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.557260,0.375563,0.181697,0.008414,1,3.492527
18355,2021-05-29,Italy,IT,4213055,126002.0,3845087.0,3348.0,83.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.565890,0.380836,0.185054,0.008426,1,3.490330
18356,2021-05-30,Italy,IT,4216003,126046.0,3851661.0,2948.0,44.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.572509,0.385052,0.187458,0.008414,1,3.488132
18357,2021-05-31,Italy,IT,4217821,126128.0,3858019.0,1818.0,82.0,60730582.0,488120.0,...,1.0,0.0,0.0,0.0,0.580401,0.390439,0.189962,0.008449,1,3.485934

In [19]:
final = final.merge(weights_df, on='date')
final

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,CanSino,Soberana02,QazVac,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations,vaccines_available,unemployment_rate_idx,weight
0,2020-03-31,United Arab Emirates,AE,664,6.0,658.0,53.0,1.0,8270684.0,96857.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0,-0.070000,1.000100
1,2020-03-31,Argentina,AR,966,24.0,942.0,0.0,0.0,43417765.0,754596.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0,0.270000,1.000100
2,2020-03-31,Australia,AU,4707,20.0,4687.0,150.0,1.0,23781169.0,303398.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0,0.140000,1.000100
3,2020-03-31,Austria,AT,10182,128.0,10054.0,564.0,20.0,8739806.0,84874.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0,0.560000,1.000100
4,2020-03-31,Belgium,BE,16987,1378.0,15609.0,1683.0,208.0,11265834.0,123040.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0,0.620000,1.000100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40969,2021-02-22,Uzbekistan,UZ,79681,622.0,78171.0,27.0,0.0,30499618.0,639665.0,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,1,0.867333,0.177878
40970,2021-02-22,Venezuela,VE,136068,1316.0,128059.0,465.0,4.0,28515829.0,NaN,...,0.0,0.0,0.0,0.000006,0.000006,0.0,0.000001,1,3.479111,0.177878
40971,2021-02-22,Viet Nam,VN,2392,35.0,1711.0,9.0,0.0,96462108.0,NaN,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,1,0.380556,0.177878
40972,2021-02-22,South Africa,ZA,1504588,49150.0,1412710.0,792.0,97.0,55291225.0,1157385.0,...,0.0,0.0,0.0,0.000417,0.000417,0.0,0.000070,1,1.264667,0.177878
40973,2021-02-22,Zambia,ZM,75027,1031.0,68457.0,524.0,11.0,17861034.0,NaN,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,1,-0.617889,0.177878

In [20]:
final[final['iso_code'] == 'CHE']

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,CanSino,Soberana02,QazVac,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations,vaccines_available,unemployment_rate_idx,weight
14,2020-03-31,Switzerland,CH,16108,373.0,15735.0,696.0,78.0,8319769.0,86914.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.590000,1.000100
110,2020-04-01,Switzerland,CH,17070,378.0,2379.0,962.0,5.0,8319769.0,86914.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.606264,0.978122
206,2020-04-02,Switzerland,CH,18194,432.0,3484.0,1124.0,54.0,8319769.0,86914.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.622527,0.956144
302,2020-04-03,Switzerland,CH,19227,484.0,4859.0,1033.0,52.0,8319769.0,86914.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.638791,0.934166
398,2020-04-04,Switzerland,CH,20201,540.0,6237.0,974.0,56.0,8319769.0,86914.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.655055,0.912188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40509,2021-05-28,Switzerland,CH,693023,10801.0,644115.0,912.0,3.0,8319769.0,86914.0,...,0.0,0.0,0.0,0.578864,0.359751,0.219113,0.009266,1,1.704396,0.274825
40605,2021-05-29,Switzerland,CH,693023,10805.0,645318.0,0.0,4.0,8319769.0,86914.0,...,0.0,0.0,0.0,0.585422,0.363212,0.222210,0.009384,1,1.702747,0.296803
40701,2021-05-30,Switzerland,CH,693023,10806.0,645321.0,0.0,1.0,8319769.0,86914.0,...,0.0,0.0,0.0,0.588386,0.364905,0.223481,0.009486,1,1.701099,0.318781
40797,2021-05-31,Switzerland,CH,694740,10810.0,647035.0,1717.0,4.0,8319769.0,86914.0,...,0.0,0.0,0.0,0.599596,0.370306,0.229290,0.010219,1,1.699451,0.340759
40892,2021-02-22,Switzerland,CH,550224,9907.0,497636.0,2449.0,20.0,8319769.0,86914.0,...,0.0,0.0,0.0,0.082659,0.057865,0.024794,0.002241,1,1.894556,0.177878

In [21]:
final.to_csv('./economic_weighted.csv', index=False)