In [9]:
import pandas as pd
import numpy as np
from datetime import datetime

## Reading the data

In [10]:
daily_country_data = pd.read_csv('./swissre/daily_country_data.csv')
geo_country_mapping = pd.read_csv('./swissre/geo_country.csv')
oxford_policies = pd.read_csv('./swissre/government_response.csv')

weather_data = pd.read_csv('./weather/weather_data.csv')

vaccinations = pd.read_csv('./vaccinations/vaccinations.csv')
type_of_vax_country = pd.read_csv('./vaccinations/type_of_vax.csv')

/Users/francescoposa/opt/anaconda3/envs/personal/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (68,69) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/Users/francescoposa/opt/anaconda3/envs/personal/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (3,4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

## Adding ISO_CODE to daily_country_data

In [11]:
type_of_vax_country[type_of_vax_country['iso_code'] == 'CHE']

,iso_code,RBD-Dimer,Sinopharm/Beijing,Abdala,Moderna,Johnson&Johnson,Covaxin,Sinovac,Oxford/AstraZeneca,Sinopharm/HayatVax,Sputnik V,Sinopharm/Wuhan,EpiVacCorona,Pfizer/BioNTech,CanSino,Soberana02,QazVac
185,CHE,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0

In [12]:
daily_country_data_columns = [
        'date',
        'name',
        'country_id',
        'cases',
        'deaths',
        'recovered',
        'new_cases',
        'new_deaths',
        'total_population_all', 
        'total_population_below_1',
        'total_population_1_to_4',
        'total_population_5_to_14',
        'total_population_15_to_24',
        'total_population_25_to_34',
        'total_population_35_to_54',
        'total_population_55_to_74',
        'total_population_above_75',
        'population_percentage_over_60',
        'hospital_beds_per_1000',
        'physicians_per_1000',
        'nurses_per_1000',
        'fatality_rate_percent',
        'cases_per_100000',
        'deaths_per_100000',
        'cases_per_1000_hospital_beds',
        'deaths_per_1000_hospital_beds',
        'cases_per_1000_nurses',
        'deaths_per_1000_nurses',
        'cases_per_1000_physicians',
        'deaths_per_1000_physicians',
        'days_since_outbreak',
        'new_cases_percent_increase',
        'avg_3d_new_cases_percent_increase',
        'unemployment_rate_2019_03_31',
        'unemployment_rate_2019_06_30',
        'unemployment_rate_2019_09_30',
        'unemployment_rate_2019_12_31',
        'unemployment_rate_2020_03_31',
        'unemployment_rate_2020_06_30',
        'unemployment_rate_2020_09_30',
        'unemployment_rate_2020_12_31',
        'unemployment_rate_2021_03_31',
        'unemployment_rate_2021_06_30',
        'unemployment_rate_2021_09_30',
        'unemployment_rate_2021_12_31',
        'gdp_2019_03_31',
        'gdp_2019_06_30',
        'gdp_2019_09_30',
        'gdp_2019_12_31',
        'gdp_2020_03_31', 
        'gdp_2020_06_30', 
        'gdp_2020_09_30', 
        'gdp_2020_12_31',
        'gdp_2021_03_31', 
        'gdp_2021_06_30', 
        'gdp_2021_09_30', 
        'gdp_2021_12_31',
        'mobility_google_retail_and_recreation',
        'mobility_google_grocery_and_pharmacy',
        'mobility_google_transit_stations',
        'mobility_google_workplace',
        'mobility_google_residential',
        'mobility_google_index',
        'mobility_google_retail_and_recreation_7d_avg',
        'mobility_google_grocery_and_pharmacy_7d_avg',
        'mobility_google_transit_stations_7d_avg',
        'mobility_google_workplace_7d_avg',
        'mobility_google_residential_7d_avg',
        'covid19_reopen_criteria_14_day_new_cases_downward_trajectory',
        'covid19_reopen_criteria_14_day_decreasing_deaths', 
        'has_implemented_introduction_of_quarantine_policies', 
        'has_implemented_public_services_closure', 
        'has_implemented_economic_measures', 
        'has_implemented_flights_suspension', 
        'has_implemented_schools_closure', 
        'has_implemented_border_closure', 
        'has_implemented_state_of_emergency_declared', 
        'has_implemented_general_lockdown', 
        'has_implemented_travel_restrictions',
        'tests',
        'tests_per_100000', 
        'new_cases_rolling_average_3',
        'new_cases_rolling_average_7',
        'new_cases_rolling_average_21',
        'new_deaths_rolling_average_3',
        'new_deaths_rolling_average_7',
        'new_deaths_rolling_average_21',
        'stage_number', #null = 0
        'epiforecasts_effective_reproduction_number_median',
        'epiforecasts_effective_reproduction_number_lower_90',
        'epiforecasts_effective_reproduction_number_upper_90',
        'epiforecasts_effective_reproduction_number_lower_50',
        'epiforecasts_effective_reproduction_number_upper_50',
        'travel_risk_score',
        'new_cases_per_100000',
        'avg_7d_new_cases_per_100k'
    ]

daily_country_data = daily_country_data[daily_country_data_columns]
daily_country_data

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,new_deaths_rolling_average_21,stage_number,epiforecasts_effective_reproduction_number_median,epiforecasts_effective_reproduction_number_lower_90,epiforecasts_effective_reproduction_number_upper_90,epiforecasts_effective_reproduction_number_lower_50,epiforecasts_effective_reproduction_number_upper_50,travel_risk_score,new_cases_per_100000,avg_7d_new_cases_per_100k
0,2020-02-03,Belgium,BE,1,0.0,1.0,1.0,0.0,11265834.0,123040.0,...,NaN,8.0,NaN,NaN,NaN,NaN,NaN,1,0.008876,0.01
1,2020-02-04,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00
2,2020-02-05,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00
3,2020-02-06,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00
4,2020-02-07,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110894,2021-01-20,Slovenia,SI,152851,3257.0,127003.0,1714.0,26.0,2063077.0,20965.0,...,28.0,NaN,0.872779,0.794162,0.957526,0.841501,0.904328,3,83.079788,68.33
110895,2021-01-21,Slovenia,SI,154306,3284.0,130137.0,1455.0,27.0,2063077.0,20965.0,...,28.0,NaN,0.875136,0.792591,0.965497,0.841865,0.908190,3,70.525724,64.39
110896,2021-01-22,Slovenia,SI,155745,3309.0,132791.0,1439.0,25.0,2063077.0,20965.0,...,28.0,NaN,0.865955,0.780914,0.951395,0.833554,0.899042,3,69.750184,62.24
110897,2021-01-23,Slovenia,SI,157293,3329.0,134949.0,1548.0,20.0,2063077.0,20965.0,...,27.0,NaN,0.855751,0.764036,0.939435,0.822721,0.888585,3,75.033554,62.63
110898,2021-01-24,Slovenia,SI,157830,3360.0,135768.0,537.0,31.0,2063077.0,20965.0,...,27.0,NaN,0.849376,0.752817,0.930966,0.813574,0.882529,3,26.029082,56.19

In [13]:
# NOTE: Namibia doesn't have an ISO_CODE, so it is dropped
geo_country_mapping = geo_country_mapping[['ISO1_ALPHA2', 'iso_1_alpha_3']].drop_duplicates().rename(columns={'ISO1_ALPHA2': 'country_id'})
geo_country_mapping = geo_country_mapping[geo_country_mapping['country_id'].isin(daily_country_data['country_id'].unique())].dropna()

merged_daily = daily_country_data.merge(geo_country_mapping, on='country_id').rename(columns={'iso_1_alpha_3': 'iso_code'})
merged_daily['date'] = pd.to_datetime(merged_daily['date']).dt.date

merged_daily

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,stage_number,epiforecasts_effective_reproduction_number_median,epiforecasts_effective_reproduction_number_lower_90,epiforecasts_effective_reproduction_number_upper_90,epiforecasts_effective_reproduction_number_lower_50,epiforecasts_effective_reproduction_number_upper_50,travel_risk_score,new_cases_per_100000,avg_7d_new_cases_per_100k,iso_code
0,2020-02-03,Belgium,BE,1,0.0,1.0,1.0,0.0,11265834.0,123040.0,...,8.0,NaN,NaN,NaN,NaN,NaN,1,0.008876,0.01,BEL
1,2020-02-04,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00,BEL
2,2020-02-05,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00,BEL
3,2020-02-06,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00,BEL
4,2020-02-07,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00,BEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110399,2021-07-18,French Polynesia,PF,19085,144.0,18887.0,0.0,0.0,279285.0,NaN,...,NaN,0.958739,0.746186,1.074247,0.893136,0.994991,1,0.000000,2.64,PYF
110400,2021-07-19,French Polynesia,PF,19085,144.0,18887.0,0.0,0.0,279285.0,NaN,...,NaN,0.958739,0.746186,1.074247,0.893136,0.994991,1,0.000000,2.64,PYF
110401,2021-07-20,French Polynesia,PF,19127,144.0,18887.0,42.0,0.0,279285.0,NaN,...,1.0,0.958739,0.746186,1.074247,0.893136,0.994991,1,15.038402,4.52,PYF
110402,2021-07-21,French Polynesia,PF,19163,144.0,18902.0,36.0,0.0,279285.0,NaN,...,1.0,0.958739,0.746186,1.074247,0.893136,0.994991,1,12.890059,5.77,PYF
110403,2021-07-22,French Polynesia,PF,19195,144.0,18902.0,32.0,0.0,279285.0,NaN,...,2.0,0.958739,0.746186,1.074247,0.893136,0.994991,1,11.457830,6.85,PYF

## Merging with OXFORD policy data

In [14]:
oxford_policies_columns = [
    'date',
    'country_name',
    'country_code',
    'school_closing',
    'workplace_closing',
    'cancel_public_events',
    'restrictions_on_gatherings',
    'close_public_transport',
    'stay_at_home_requirements',
    'public_information_campaigns',
    'testing_policy',
    'vaccination_policy',
    'contact_tracing',
    'restrictions_on_internal_movement',
    'international_travel_controls',
    'fiscal_measures',
    'monetary_measures',
    'emergency_investment_in_health_care',
    'investment_in_vaccines',
]

oxford_policies = oxford_policies[(oxford_policies['region_name'].isna()) & (oxford_policies['region_code'].isna())][oxford_policies_columns]
oxford_policies = oxford_policies.rename(columns={"country_code": "iso_code"})
oxford_policies['date'] = pd.to_datetime(oxford_policies['date']).dt.date
oxford_policies

,date,country_name,iso_code,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,close_public_transport,stay_at_home_requirements,public_information_campaigns,testing_policy,vaccination_policy,contact_tracing,restrictions_on_internal_movement,international_travel_controls,fiscal_measures,monetary_measures,emergency_investment_in_health_care,investment_in_vaccines
0,2020-01-01,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
1,2020-01-02,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
2,2020-01-03,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
3,2020-01-04,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
4,2020-01-05,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177211,2021-07-17,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177212,2021-07-18,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177213,2021-07-19,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177214,2021-07-20,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177215,2021-07-21,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Some countries are dropped
set(merged_daily['iso_code'].unique()) - set(oxford_policies['iso_code'].unique())

{'AIA',
 'ARM',
 'ATG',
 'BES',
 'BLM',
 'CUW',
 'CYM',
 'ESH',
 'FLK',
 'FSM',
 'GGY',
 'GIB',
 'GLP',
 'GNB',
 'GNQ',
 'GRD',
 'GUF',
 'IMN',
 'JEY',
 'KNA',
 'LCA',
 'MAF',
 'MDV',
 'MHL',
 'MKD',
 'MNE',
 'MNP',
 'MSR',
 'MTQ',
 'MYT',
 'NCL',
 'PYF',
 'REU',
 'SPM',
 'STP',
 'SXM',
 'TCA',
 'VAT',
 'VCT',
 'VGB',
 'WLF',
 'WSM'}

In [16]:
# Some countries are dropped
set(oxford_policies['iso_code'].unique()) - set(merged_daily['iso_code'].unique())

{'MAC', 'NAM', 'RKS', 'TKM', 'TON'}

In [17]:
merged_daily = merged_daily.merge(oxford_policies, on=['iso_code', 'date'])
merged_daily

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,public_information_campaigns,testing_policy,vaccination_policy,contact_tracing,restrictions_on_internal_movement,international_travel_controls,fiscal_measures,monetary_measures,emergency_investment_in_health_care,investment_in_vaccines
0,2020-02-03,Belgium,BE,1,0.0,1.0,1.0,0.0,11265834.0,123040.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
1,2020-02-04,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
2,2020-02-05,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
3,2020-02-06,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
4,2020-02-07,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90676,2021-07-17,Mozambique,MZ,98152,1099.0,76269.0,2025.0,24.0,30366043.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90677,2021-07-18,Mozambique,MZ,99412,1118.0,76716.0,1260.0,19.0,30366043.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90678,2021-07-19,Mozambique,MZ,100785,1138.0,76839.0,1373.0,20.0,30366043.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90679,2021-07-20,Mozambique,MZ,102009,1158.0,78043.0,1224.0,20.0,30366043.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90680,2021-07-21,Mozambique,MZ,103713,1190.0,80009.0,1704.0,32.0,30366043.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Merging with weather_data

In [18]:
weather_data['date'] = pd.to_datetime(weather_data['date']).dt.date
weather_data

,date,iso_code,maxtempC,mintempC,tempC,FeelsLikeC,HeatIndexC,humidity,pressure,uvIndex,totalSnow_cm,sunHour,windspeedKmph,precipMM
0,2020-01-01,AFG,3,-1,3,-2,1,46,1026,1,0.1,3.6,9,0.4
1,2020-01-02,AFG,-1,-4,-1,-4,-2,95,1028,1,4.5,3.6,5,6.5
2,2020-01-03,AFG,-1,-6,-1,-5,-4,87,1026,1,0.5,7.0,5,0.9
3,2020-01-04,AFG,4,-3,4,-2,0,42,1023,2,0.0,8.7,6,0.0
4,2020-01-05,AFG,2,-4,2,-3,-2,52,1022,1,1.0,5.3,5,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125052,2021-05-27,MOZ,26,18,26,22,22,67,1020,6,0.0,8.7,9,0.0
125053,2021-05-28,MOZ,31,17,31,23,23,46,1015,6,0.0,8.7,12,0.0
125054,2021-05-29,MOZ,25,18,25,21,21,76,1016,6,0.0,8.7,13,0.0
125055,2021-05-30,MOZ,22,18,22,19,20,75,1020,5,0.0,4.0,14,0.2
125056,2021-05-31,MOZ,21,16,21,19,19,67,1022,4,0.0,5.6,11,0.0

In [19]:
merged_daily = merged_daily.merge(weather_data, on=['iso_code', 'date'])
merged_daily

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,tempC,FeelsLikeC,HeatIndexC,humidity,pressure,uvIndex,totalSnow_cm,sunHour,windspeedKmph,precipMM
0,2020-02-03,Belgium,BE,1,0.0,1.0,1.0,0.0,11265834.0,123040.0,...,10,6,9,80,1013,2,0.0,3.5,24,6.7
1,2020-02-04,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,5,0,4,79,1017,1,0.0,3.5,20,9.7
2,2020-02-05,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,8,4,5,80,1034,3,0.0,8.7,6,0.0
3,2020-02-06,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,9,5,6,81,1031,2,0.0,8.7,4,0.0
4,2020-02-07,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,10,4,6,73,1024,3,0.0,8.7,12,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81398,2021-05-27,Mozambique,MZ,70673,834.0,69215.0,22.0,0.0,30366043.0,NaN,...,26,22,22,67,1020,6,0.0,8.7,9,0.0
81399,2021-05-28,Mozambique,MZ,70697,835.0,69232.0,24.0,1.0,30366043.0,NaN,...,31,23,23,46,1015,6,0.0,8.7,12,0.0
81400,2021-05-29,Mozambique,MZ,70724,836.0,69258.0,27.0,1.0,30366043.0,NaN,...,25,21,21,76,1016,6,0.0,8.7,13,0.0
81401,2021-05-30,Mozambique,MZ,70780,836.0,69507.0,56.0,0.0,30366043.0,NaN,...,22,19,20,75,1020,5,0.0,4.0,14,0.2
81402,2021-05-31,Mozambique,MZ,70795,836.0,69522.0,15.0,0.0,30366043.0,NaN,...,21,19,19,67,1022,4,0.0,5.6,11,0.0

## Mergining with vaccinations

In [20]:
merged_daily = merged_daily.merge(type_of_vax_country, on='iso_code', how='left')

In [21]:
vaccinations = vaccinations[vaccinations.iso_code.isin(list(merged_daily.iso_code.unique()))]
vaccinations['date'] = pd.to_datetime(vaccinations['date']).dt.date

# Getting first day of vaccinations for each country
mapping = {}
for iso_code in vaccinations.iso_code.unique():
    temp = vaccinations[vaccinations.iso_code == iso_code].sort_values('date')
    mapping[iso_code] = temp.date.values[0]
    
merged_daily = merged_daily.merge(vaccinations, on=['iso_code', 'date'], how='left')
merged_daily = merged_daily[~merged_daily['total_population_all'].isna()]
merged_daily

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,Sinopharm/Wuhan,EpiVacCorona,Pfizer/BioNTech,CanSino,Soberana02,QazVac,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations
0,2020-02-03,Belgium,BE,1,0.0,1.0,1.0,0.0,11265834.0,123040.0,...,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,2020-02-04,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,2020-02-05,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,2020-02-06,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
4,2020-02-07,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81398,2021-05-27,Mozambique,MZ,70673,834.0,69215.0,22.0,0.0,30366043.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,412217.0,337491.0,74726.0,93.0
81399,2021-05-28,Mozambique,MZ,70697,835.0,69232.0,24.0,1.0,30366043.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,412310.0,337565.0,74745.0,93.0
81400,2021-05-29,Mozambique,MZ,70724,836.0,69258.0,27.0,1.0,30366043.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,412403.0,337640.0,74763.0,93.0
81401,2021-05-30,Mozambique,MZ,70780,836.0,69507.0,56.0,0.0,30366043.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,412496.0,337714.0,74782.0,93.0
81402,2021-05-31,Mozambique,MZ,70795,836.0,69522.0,15.0,0.0,30366043.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,394312.0,319511.0,74801.0,93.0

In [22]:
# First vaccine ever recorded:
[v for k, v in sorted(mapping.items(), key=lambda item: item[1])][0]

datetime.date(2020, 12, 2)

In [23]:
merged_daily['vaccines_available'] = np.where(merged_daily.date < datetime.strptime('2020-12-14', '%Y-%m-%d').date(), 0, 1)

In [24]:
for iso_code in merged_daily.iso_code.unique():
    if iso_code in mapping.keys():
        starting_date = mapping[iso_code]
        merged_daily['total_vaccinations'] = np.where((merged_daily['iso_code']==iso_code) & (merged_daily['date'] < starting_date), 0, merged_daily['total_vaccinations'])
        merged_daily['people_fully_vaccinated'] = np.where((merged_daily['iso_code']==iso_code) & (merged_daily['date'] < starting_date), 0, merged_daily['people_fully_vaccinated'])
        merged_daily['people_vaccinated'] = np.where((merged_daily['iso_code']==iso_code) & (merged_daily['date'] < starting_date), 0, merged_daily['people_vaccinated'])
        merged_daily['daily_vaccinations'] = np.where((merged_daily['iso_code']==iso_code) & (merged_daily['date'] < starting_date), 0, merged_daily['daily_vaccinations'])
        
        # Considering percentages
        merged_daily['total_vaccinations'] = np.where((merged_daily['iso_code']==iso_code), merged_daily['total_vaccinations'] / merged_daily['total_population_all'], merged_daily['total_vaccinations'])
        merged_daily['people_fully_vaccinated'] = np.where((merged_daily['iso_code']==iso_code), merged_daily['people_fully_vaccinated'] / merged_daily['total_population_all'], merged_daily['people_fully_vaccinated'])
        merged_daily['people_vaccinated'] = np.where((merged_daily['iso_code']==iso_code), merged_daily['people_vaccinated'] / merged_daily['total_population_all'], merged_daily['people_vaccinated'])
        merged_daily['daily_vaccinations'] = np.where((merged_daily['iso_code']==iso_code), merged_daily['daily_vaccinations'] / merged_daily['total_population_all'], merged_daily['daily_vaccinations'])
    else:
        print(iso_code)

GUM
KIR
BDI
ERI
PRI
TZA
VIR

In [25]:
merged_daily.sort_values(by=['iso_code', 'date']).to_csv('./final_data.csv', index=False)

In [26]:
merged_daily[merged_daily['iso_code'] == 'CHE']['EpiVacCorona']

484    0.0
485    0.0
486    0.0
487    0.0
488    0.0
      ...
941    0.0
942    0.0
943    0.0
944    0.0
945    0.0
Name: EpiVacCorona, Length: 462, dtype: float64

## SwissRE platform data generation

In [27]:
# Extracting datast on vaccines for the platform
vacc = merged_daily[['iso_code', 'date', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'daily_vaccinations']]
for iso_code in vacc.iso_code.unique():
    if iso_code in mapping.keys():
        starting_date = mapping[iso_code]
        vacc = vacc.drop(vacc[(vacc.date < starting_date) & (vacc.iso_code == iso_code)].index)
    else:
        vacc = vacc.drop(vacc[(vacc.iso_code == iso_code)].index)
vacc

,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations
329,BEL,2020-12-28,0.000027,0.000027,0.000000,0.000027
330,BEL,2020-12-29,0.000029,0.000029,0.000000,0.000002
331,BEL,2020-12-30,0.000072,0.000072,0.000000,0.000023
332,BEL,2020-12-31,0.000074,0.000074,0.000000,0.000016
333,BEL,2021-01-01,0.000074,0.000074,0.000000,0.000012
...,...,...,...,...,...,...
81398,MOZ,2021-05-27,0.013575,0.011114,0.002461,0.000003
81399,MOZ,2021-05-28,0.013578,0.011117,0.002461,0.000003
81400,MOZ,2021-05-29,0.013581,0.011119,0.002462,0.000003
81401,MOZ,2021-05-30,0.013584,0.011121,0.002463,0.000003
81402,MOZ,2021-05-31,0.012985,0.010522,0.002463,0.000003

In [28]:
vacc.sort_values(by=['iso_code', 'date']).to_csv('./vaccination_percentages.csv', index = False)