In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

## Reading the data

In [2]:
daily_country_data = pd.read_csv('./swissre/daily_country_data.csv')
geo_country_mapping = pd.read_csv('./swissre/geo_country.csv')
oxford_policies = pd.read_csv('./swissre/government_response.csv')

weather_data = pd.read_csv('./weather/weather_data.csv')

vaccinations = pd.read_csv('./vaccinations/vaccinations.csv')
type_of_vax_country = pd.read_csv('./vaccinations/type_of_vax.csv')

/Users/francescoposa/opt/anaconda3/envs/personal/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (124,129,130,131,148,149,150,210,211,212,213,214,215,216,217,232,233,234,235,236,237,238,239,240,280,281) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/Users/francescoposa/opt/anaconda3/envs/personal/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (3,4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

## Adding ISO_CODE to daily_country_data

In [3]:
daily_country_data_columns = [
        'date',
        'name',
        'country_id',
        'cases',
        'deaths',
        'recovered',
        'new_cases',
        'new_deaths',
        'total_population_all', 
        'total_population_below_1',
        'total_population_1_to_4',
        'total_population_5_to_14',
        'total_population_15_to_24',
        'total_population_25_to_34',
        'total_population_35_to_54',
        'total_population_55_to_74',
        'total_population_above_75',
        'population_percentage_over_60',
        'hospital_beds_per_1000',
        'physicians_per_1000',
        'nurses_per_1000',
        'fatality_rate_percent',
        'cases_per_100000',
        'deaths_per_100000',
        'cases_per_1000_hospital_beds',
        'deaths_per_1000_hospital_beds',
        'cases_per_1000_nurses',
        'deaths_per_1000_nurses',
        'cases_per_1000_physicians',
        'deaths_per_1000_physicians',
        'days_since_outbreak',
        'new_cases_percent_increase',
        'avg_3d_new_cases_percent_increase',
        'unemployment_rate_2019_03_31',
        'unemployment_rate_2019_06_30',
        'unemployment_rate_2019_09_30',
        'unemployment_rate_2019_12_31',
        'unemployment_rate_2020_03_31',
        'unemployment_rate_2020_06_30',
        'unemployment_rate_2020_09_30',
        'unemployment_rate_2020_12_31',
        'unemployment_rate_2021_03_31',
        'unemployment_rate_2021_06_30',
        'unemployment_rate_2021_09_30',
        'unemployment_rate_2021_12_31',
        'gdp_2019_03_31',
        'gdp_2019_06_30',
        'gdp_2019_09_30',
        'gdp_2019_12_31',
        'gdp_2020_03_31', 
        'gdp_2020_06_30', 
        'gdp_2020_09_30', 
        'gdp_2020_12_31',
        'gdp_2021_03_31', 
        'gdp_2021_06_30', 
        'gdp_2021_09_30', 
        'gdp_2021_12_31',
        'mobility_google_retail_and_recreation',
        'mobility_google_grocery_and_pharmacy',
        'mobility_google_transit_stations',
        'mobility_google_workplace',
        'mobility_google_residential',
        'mobility_google_index',
        'mobility_google_retail_and_recreation_7d_avg',
        'mobility_google_grocery_and_pharmacy_7d_avg',
        'mobility_google_transit_stations_7d_avg',
        'mobility_google_workplace_7d_avg',
        'mobility_google_residential_7d_avg',
        'covid19_reopen_criteria_14_day_new_cases_downward_trajectory',
        'covid19_reopen_criteria_14_day_decreasing_deaths', 
        'has_implemented_introduction_of_quarantine_policies', 
        'has_implemented_public_services_closure', 
        'has_implemented_economic_measures', 
        'has_implemented_flights_suspension', 
        'has_implemented_schools_closure', 
        'has_implemented_border_closure', 
        'has_implemented_state_of_emergency_declared', 
        'has_implemented_general_lockdown', 
        'has_implemented_travel_restrictions',
        'tests',
        'tests_per_100000', 
        'new_cases_rolling_average_3',
        'new_cases_rolling_average_7',
        'new_cases_rolling_average_21',
        'new_deaths_rolling_average_3',
        'new_deaths_rolling_average_7',
        'new_deaths_rolling_average_21',
        'stage_number', #null = 0
        'epiforecasts_effective_reproduction_number_median',
        'epiforecasts_effective_reproduction_number_lower_90',
        'epiforecasts_effective_reproduction_number_upper_90',
        'epiforecasts_effective_reproduction_number_lower_50',
        'epiforecasts_effective_reproduction_number_upper_50',
        'travel_risk_score',
        'new_cases_per_100000',
        'avg_7d_new_cases_per_100k'
    ]

daily_country_data = daily_country_data[daily_country_data_columns]
daily_country_data

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,new_deaths_rolling_average_21,stage_number,epiforecasts_effective_reproduction_number_median,epiforecasts_effective_reproduction_number_lower_90,epiforecasts_effective_reproduction_number_upper_90,epiforecasts_effective_reproduction_number_lower_50,epiforecasts_effective_reproduction_number_upper_50,travel_risk_score,new_cases_per_100000,avg_7d_new_cases_per_100k
0,2020-02-03T00:00:00.000Z,Belgium,BE,1,0.0,1.0,1.0,0.0,11265834.0,123040.0,...,NaN,8.0,NaN,NaN,NaN,NaN,NaN,1,0.008876,0.01
1,2020-02-04T00:00:00.000Z,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00
2,2020-02-05T00:00:00.000Z,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00
3,2020-02-06T00:00:00.000Z,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00
4,2020-02-07T00:00:00.000Z,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90478,2021-04-17T00:00:00.000Z,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,8.0,6.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.49
90479,2021-04-18T00:00:00.000Z,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,8.0,6.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.49
90480,2021-04-19T00:00:00.000Z,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,8.0,6.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.49
90481,2021-04-20T00:00:00.000Z,Sudan,SD,32546,2287.0,26248.0,756.0,79.0,42813237.0,NaN,...,8.0,6.0,NaN,NaN,NaN,NaN,NaN,1,1.765809,0.71
90482,2021-04-21T00:00:00.000Z,Sudan,SD,32611,2289.0,26311.0,65.0,2.0,42813237.0,NaN,...,11.0,6.0,NaN,NaN,NaN,NaN,NaN,1,0.151822,0.27

In [4]:
# NOTE: Namibia doesn't have an ISO_CODE, so it is dropped
geo_country_mapping = geo_country_mapping[['ISO1_ALPHA2', 'iso_1_alpha_3']].drop_duplicates().rename(columns={'ISO1_ALPHA2': 'country_id'})
geo_country_mapping = geo_country_mapping[geo_country_mapping['country_id'].isin(daily_country_data['country_id'].unique())].dropna()

merged_daily = daily_country_data.merge(geo_country_mapping, on='country_id').rename(columns={'iso_1_alpha_3': 'iso_code'})
merged_daily['date'] = pd.to_datetime(merged_daily['date']).dt.date

merged_daily

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,stage_number,epiforecasts_effective_reproduction_number_median,epiforecasts_effective_reproduction_number_lower_90,epiforecasts_effective_reproduction_number_upper_90,epiforecasts_effective_reproduction_number_lower_50,epiforecasts_effective_reproduction_number_upper_50,travel_risk_score,new_cases_per_100000,avg_7d_new_cases_per_100k,iso_code
0,2020-02-03,Belgium,BE,1,0.0,1.0,1.0,0.0,11265834.0,123040.0,...,8.0,NaN,NaN,NaN,NaN,NaN,1,0.008876,0.01,BEL
1,2020-02-04,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00,BEL
2,2020-02-05,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00,BEL
3,2020-02-06,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00,BEL
4,2020-02-07,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,8.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.00,BEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90074,2021-04-17,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,6.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.49,SDN
90075,2021-04-18,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,6.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.49,SDN
90076,2021-04-19,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,6.0,NaN,NaN,NaN,NaN,NaN,1,0.000000,0.49,SDN
90077,2021-04-20,Sudan,SD,32546,2287.0,26248.0,756.0,79.0,42813237.0,NaN,...,6.0,NaN,NaN,NaN,NaN,NaN,1,1.765809,0.71,SDN
90078,2021-04-21,Sudan,SD,32611,2289.0,26311.0,65.0,2.0,42813237.0,NaN,...,6.0,NaN,NaN,NaN,NaN,NaN,1,0.151822,0.27,SDN

## Merging with OXFORD policy data

In [5]:
oxford_policies_columns = [
    'date',
    'country_name',
    'country_code',
    'school_closing',
    'workplace_closing',
    'cancel_public_events',
    'restrictions_on_gatherings',
    'close_public_transport',
    'stay_at_home_requirements',
    'public_information_campaigns',
    'testing_policy',
    'vaccination_policy',
    'contact_tracing',
    'restrictions_on_internal_movement',
    'international_travel_controls',
    'fiscal_measures',
    'monetary_measures',
    'emergency_investment_in_health_care',
    'investment_in_vaccines',
]

oxford_policies = oxford_policies[(oxford_policies['region_name'].isna()) & (oxford_policies['region_code'].isna())][oxford_policies_columns]
oxford_policies = oxford_policies.rename(columns={"country_code": "iso_code"})
oxford_policies['date'] = pd.to_datetime(oxford_policies['date']).dt.date
oxford_policies

,date,country_name,iso_code,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,close_public_transport,stay_at_home_requirements,public_information_campaigns,testing_policy,vaccination_policy,contact_tracing,restrictions_on_internal_movement,international_travel_controls,fiscal_measures,monetary_measures,emergency_investment_in_health_care,investment_in_vaccines
0,2020-01-01,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
1,2020-01-02,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
2,2020-01-03,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
3,2020-01-04,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
4,2020-01-05,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134032,2021-04-17,Zimbabwe,ZWE,1.0,2.0,2.0,3.0,1.0,2.0,2.0,3.0,4.0,0.0,0.0,1.0,0.0,NaN,0.0,0.0
134033,2021-04-18,Zimbabwe,ZWE,1.0,2.0,2.0,3.0,1.0,2.0,2.0,3.0,4.0,0.0,0.0,1.0,0.0,NaN,0.0,0.0
134034,2021-04-19,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134035,2021-04-20,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134036,2021-04-21,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Some countries are dropped
set(merged_daily['iso_code'].unique()) - set(oxford_policies['iso_code'].unique())

{'AIA',
 'ARM',
 'ATG',
 'BES',
 'BLM',
 'CUW',
 'CYM',
 'ESH',
 'FLK',
 'FSM',
 'GGY',
 'GIB',
 'GLP',
 'GNB',
 'GNQ',
 'GRD',
 'GUF',
 'IMN',
 'JEY',
 'KNA',
 'LCA',
 'MAF',
 'MDV',
 'MHL',
 'MKD',
 'MNE',
 'MNP',
 'MSR',
 'MTQ',
 'MYT',
 'NCL',
 'PYF',
 'REU',
 'SPM',
 'STP',
 'SXM',
 'TCA',
 'VAT',
 'VCT',
 'VGB',
 'WLF',
 'WSM'}

In [7]:
# Some countries are dropped
set(oxford_policies['iso_code'].unique()) - set(merged_daily['iso_code'].unique())

{'KIR', 'MAC', 'NAM', 'RKS', 'TKM', 'TON'}

In [8]:
merged_daily = merged_daily.merge(oxford_policies, on=['iso_code', 'date'])
merged_daily

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,public_information_campaigns,testing_policy,vaccination_policy,contact_tracing,restrictions_on_internal_movement,international_travel_controls,fiscal_measures,monetary_measures,emergency_investment_in_health_care,investment_in_vaccines
0,2020-02-03,Belgium,BE,1,0.0,1.0,1.0,0.0,11265834.0,123040.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
1,2020-02-04,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
2,2020-02-05,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
3,2020-02-06,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
4,2020-02-07,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74231,2021-04-17,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74232,2021-04-18,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74233,2021-04-19,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74234,2021-04-20,Sudan,SD,32546,2287.0,26248.0,756.0,79.0,42813237.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74235,2021-04-21,Sudan,SD,32611,2289.0,26311.0,65.0,2.0,42813237.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Merging with weather_data

In [9]:
weather_data['date'] = pd.to_datetime(weather_data['date']).dt.date
weather_data

,date,iso_code,maxtempC,mintempC,tempC,FeelsLikeC,HeatIndexC,humidity,pressure,uvIndex,totalSnow_cm,sunHour,windspeedKmph,precipMM
0,2020-01-01,AFG,3,-1,3,-2,1,46,1026,1,0.1,3.6,9,0.4
1,2020-01-02,AFG,-1,-4,-1,-4,-2,95,1028,1,4.5,3.6,5,6.5
2,2020-01-03,AFG,-1,-6,-1,-5,-4,87,1026,1,0.5,7.0,5,0.9
3,2020-01-04,AFG,4,-3,4,-2,0,42,1023,2,0.0,8.7,6,0.0
4,2020-01-05,AFG,2,-4,2,-3,-2,52,1022,1,1.0,5.3,5,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115382,2021-04-17,MOZ,23,18,23,20,21,59,1026,5,0.0,5.7,15,0.5
115383,2021-04-18,MOZ,25,16,25,21,21,65,1024,6,0.0,8.7,10,0.0
115384,2021-04-19,MOZ,27,17,27,22,22,68,1021,6,0.0,8.7,12,0.0
115385,2021-04-20,MOZ,25,19,25,23,23,72,1022,5,0.0,4.2,10,1.9
115386,2021-04-21,MOZ,28,18,28,24,24,70,1021,6,0.0,8.7,10,0.0

In [10]:
merged_daily = merged_daily.merge(weather_data, on=['iso_code', 'date'])
merged_daily

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,tempC,FeelsLikeC,HeatIndexC,humidity,pressure,uvIndex,totalSnow_cm,sunHour,windspeedKmph,precipMM
0,2020-02-03,Belgium,BE,1,0.0,1.0,1.0,0.0,11265834.0,123040.0,...,10,6,9,80,1013,2,0.0,3.5,24,6.7
1,2020-02-04,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,5,0,4,79,1017,1,0.0,3.5,20,9.7
2,2020-02-05,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,8,4,5,80,1034,3,0.0,8.7,6,0.0
3,2020-02-06,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,9,5,6,81,1031,2,0.0,8.7,4,0.0
4,2020-02-07,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,10,4,6,73,1024,3,0.0,8.7,12,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74193,2021-04-17,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,39,31,31,6,1007,8,0.0,12.7,17,0.0
74194,2021-04-18,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,41,33,33,7,1007,9,0.0,12.7,14,0.0
74195,2021-04-19,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,42,36,36,12,1006,9,0.0,12.7,13,0.0
74196,2021-04-20,Sudan,SD,32546,2287.0,26248.0,756.0,79.0,42813237.0,NaN,...,43,37,37,11,1004,9,0.0,12.7,11,0.0
74197,2021-04-21,Sudan,SD,32611,2289.0,26311.0,65.0,2.0,42813237.0,NaN,...,43,37,37,9,1003,9,0.0,12.7,12,0.0

## Mergining with vaccinations

In [11]:
merged_daily = merged_daily.merge(type_of_vax_country, on='iso_code', how='left')

In [12]:
vaccinations = vaccinations[vaccinations.iso_code.isin(list(merged_daily.iso_code.unique()))]
vaccinations['date'] = pd.to_datetime(vaccinations['date']).dt.date

# Getting first day of vaccinations for each country
mapping = {}
for iso_code in vaccinations.iso_code.unique():
    temp = vaccinations[vaccinations.iso_code == iso_code].sort_values('date')
    mapping[iso_code] = temp.date.values[0]
    
merged_daily = merged_daily.merge(vaccinations, on=['iso_code', 'date'], how='left')
merged_daily = merged_daily[~merged_daily['total_population_all'].isna()]
merged_daily

,date,name,country_id,cases,deaths,recovered,new_cases,new_deaths,total_population_all,total_population_below_1,...,Sinovac,Sinopharm/Wuhan,Pfizer/BioNTech,Johnson&Johnson,Oxford/AstraZeneca,CanSino,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations
0,2020-02-03,Belgium,BE,1,0.0,1.0,1.0,0.0,11265834.0,123040.0,...,0.0,0.0,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
1,2020-02-04,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,0.0,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
2,2020-02-05,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,0.0,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
3,2020-02-06,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,0.0,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
4,2020-02-07,Belgium,BE,1,0.0,1.0,0.0,0.0,11265834.0,123040.0,...,0.0,0.0,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74193,2021-04-17,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
74194,2021-04-18,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
74195,2021-04-19,Sudan,SD,31790,2208.0,25539.0,0.0,0.0,42813237.0,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
74196,2021-04-20,Sudan,SD,32546,2287.0,26248.0,756.0,79.0,42813237.0,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
74197,2021-04-21,Sudan,SD,32611,2289.0,26311.0,65.0,2.0,42813237.0,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN

In [13]:
# First vaccine ever recorded:
[v for k, v in sorted(mapping.items(), key=lambda item: item[1])][0]

datetime.date(2020, 12, 14)

In [14]:
merged_daily['vaccines_available'] = np.where(merged_daily.date < datetime.strptime('2020-12-14', '%Y-%m-%d').date(), 0, 1)

In [15]:
for iso_code in merged_daily.iso_code.unique():
    if iso_code in mapping.keys():
        starting_date = mapping[iso_code]
        merged_daily['total_vaccinations'] = np.where((merged_daily['iso_code']==iso_code) & (merged_daily['date'] < starting_date), 0, merged_daily['total_vaccinations'])
        merged_daily['people_fully_vaccinated'] = np.where((merged_daily['iso_code']==iso_code) & (merged_daily['date'] < starting_date), 0, merged_daily['people_fully_vaccinated'])
        merged_daily['people_vaccinated'] = np.where((merged_daily['iso_code']==iso_code) & (merged_daily['date'] < starting_date), 0, merged_daily['people_vaccinated'])
        merged_daily['daily_vaccinations'] = np.where((merged_daily['iso_code']==iso_code) & (merged_daily['date'] < starting_date), 0, merged_daily['daily_vaccinations'])
        
        # Considering percentages
        merged_daily['total_vaccinations'] = np.where((merged_daily['iso_code']==iso_code), merged_daily['total_vaccinations'] / merged_daily['total_population_all'], merged_daily['total_vaccinations'])
        merged_daily['people_fully_vaccinated'] = np.where((merged_daily['iso_code']==iso_code), merged_daily['people_fully_vaccinated'] / merged_daily['total_population_all'], merged_daily['people_fully_vaccinated'])
        merged_daily['people_vaccinated'] = np.where((merged_daily['iso_code']==iso_code), merged_daily['people_vaccinated'] / merged_daily['total_population_all'], merged_daily['people_vaccinated'])
        merged_daily['daily_vaccinations'] = np.where((merged_daily['iso_code']==iso_code), merged_daily['daily_vaccinations'] / merged_daily['total_population_all'], merged_daily['daily_vaccinations'])
    else:
        print(iso_code)

GUM
MDG
YEM
TCD
HTI
LBY
ERI
LBR
PRI
COD
TJK
DJI
BEN
CAF
CUB
SOM
VUT
BFA
BDI
TZA
COM
VIR

In [16]:
merged_daily.sort_values(by=['iso_code', 'date']).to_csv('./final_data.csv', index=False)

## SwissRE platform data generation

In [17]:
# Extracting datast on vaccines for the platform
vacc = merged_daily[['iso_code', 'date', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'daily_vaccinations']]
for iso_code in vacc.iso_code.unique():
    if iso_code in mapping.keys():
        starting_date = mapping[iso_code]
        vacc = vacc.drop(vacc[(vacc.date < starting_date) & (vacc.iso_code == iso_code)].index)
    else:
        vacc = vacc.drop(vacc[(vacc.iso_code == iso_code)].index)
vacc

,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations
329,BEL,2020-12-28,0.000026,0.000026,0.0,2.645166e-05
330,BEL,2020-12-29,0.000027,0.000027,0.0,8.876396e-08
331,BEL,2020-12-30,0.000069,0.000069,0.0,2.130335e-05
332,BEL,2020-12-31,0.000070,0.000070,0.0,1.446852e-05
333,BEL,2021-01-01,0.000070,0.000070,0.0,1.100673e-05
...,...,...,...,...,...,...
74193,SDN,2021-04-17,NaN,NaN,NaN,NaN
74194,SDN,2021-04-18,NaN,NaN,NaN,NaN
74195,SDN,2021-04-19,NaN,NaN,NaN,NaN
74196,SDN,2021-04-20,NaN,NaN,NaN,NaN
74197,SDN,2021-04-21,NaN,NaN,NaN,NaN

In [18]:
vacc.sort_values(by=['iso_code', 'date']).to_csv('./vaccination_percentages.csv', index = False)